name: Build/Test Cyclus

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-test-cyclus:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]

    steps:
      - name: Checkout Cyclus
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Cyclus
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          file: docker/Dockerfile
          tags: |
            ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}

  downstream-cycamore:
    runs-on: ubuntu-latest
    needs: build-test-cyclus
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      build-failure: ${{ steps.build-cycamore.outcome }} != 'success'
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]

    steps:
      - name: Checkout Cycamore
        uses: actions/checkout@v4
        with:
          repository: cyclus/cycamore
          ref: main
          path: ${{ github.workspace }}/cycamore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Cycamore
        id: build-cycamore
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          context: ${{ github.workspace }}/cycamore
          file: ${{ github.workspace }}/cycamore/docker/Dockerfile
          tags: |
            ghcr.io/cyclus/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}

  downstream-cymetric:
    runs-on: ubuntu-latest
    needs: [build-test-cyclus, downstream-cycamore]
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      build-failure: ${{ steps.build-cymetric.outcome }} != 'success'
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]

    steps:
      - name: Checkout Cymetric
        uses: actions/checkout@v4
        with:
          repository: cyclus/cymetric
          ref: main
          path: ${{ github.workspace }}/cymetric

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Cymetric
        id: build-cymetric
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          context: ${{ github.workspace }}/cymetric
          file: ${{ github.workspace }}/cycamore/docker/Dockerfile
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}
  
  comment-downstream-statuses:
    runs-on: ubuntu-latest
    needs: [build-test-cyclus, downstream-cycamore, downstream-cymetric]
    permissions:
      pull-requests: write

    steps:
      - name: PR Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: downstream_statuses
          message: |
            ## Downstream Build Statuses using Cyclus ${{ github.ref }}
            - Cycamore: ${{needs.downstream-cycamore.outputs.build-failure && '**Failure**' || '*Success*'}}
            - Cymetric: ${{needs.downstream-cymetric.outputs.build-failure && '**Failure**' || '*Success*'}}