name: Code Coverage

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test.yml'
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]
    
    name: Build, Test, Report Coverage
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Cyclus
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, Test, and Report Coverage
        uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus-coverage:ci-layer-cache
          cache-to: type=registry,ref=ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus-coverage:ci-layer-cache,mode=max
          file: docker/Dockerfile
          target: cyclus-coverage
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}
          secrets: |
            "coveralls_flags=--compare-ref ${{ github.base_ref }} --service github \
            --parallel --job-flag ${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }} \
            --build-number ${{ github.run_id }} -r ${{ secrets.GITHUB_TOKEN }}"
        
  finish-coveralls:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Done
      run: |
        curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz
        ./coveralls done --build-number ${{ github.run_id }}
        
