name: Publish Cyclus Release

on:
  release:
    types: [published]

jobs:
  build-and-test-for-release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda
        ]

    name: Installing Dependencies, Building cyclus and running tests
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Cyclus Image
        uses: bennibbelink/cyclus-ci-action@main
        with:
          repository: cyclus/cyclus
          push-image: true
          artifact-out-name: cyclus-${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}
          artifact-out-tags: |
            ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:${{ github.ref_name }}
          dockerfile-path: docker/Dockerfile
          docker-build-target: cyclus
          docker-build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}